In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import os
os.getcwd()

'/content'

In [0]:
os.chdir('/content/drive/My Drive/Day 28')


In [0]:
import pandas as pd
dataset=pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.sample()

RowNumber  CustomerId Surname  ...  IsActiveMember EstimatedSalary Exited
3095       3096    15680243   Brown  ...               0        33282.84      0

[1 rows x 14 columns]

In [7]:
dataset.shape

(10000, 14)

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
features=dataset.iloc[:,3:13].values
labels=dataset.iloc[:,13].values

In [23]:
features[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [132]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_features_1 = LabelEncoder()
features[:, 1] = labelencoder_features_1.fit_transform(features[:, 1])

labelencoder_features_2 = LabelEncoder()
features[:, 2] = labelencoder_features_2.fit_transform(features[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
features = onehotencoder.fit_transform(features).toarray()

features = features[:, 1:] #dummy variable trap

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test=train_test_split(features, labels, test_size=0.20, random_state=0)


In [0]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
features_train=ss.fit_transform(features_train)
features_test=ss.transform(features_test)

In [27]:
features.shape

(10000, 11)

In [28]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
classifier=Sequential()

In [34]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

In [0]:
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

In [0]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [39]:
classifier.fit(features_train, labels_train, batch_size=10, epochs=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
8000/8000 [==============================] - 2s 193us/step - loss: 0.4825 - acc: 0.7960
Epoch 2/10
8000/8000 [==============================] - 1s 91us/step - loss: 0.4163 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 1s 105us/step - loss: 0.4066 - acc: 0.8055
Epoch 4/10
8000/8000 [==============================] - 1s 90us/step - loss: 0.3968 - acc: 0.8270
Epoch 5/10
8000/8000 [==============================] - 1s 89us/step - loss: 0.3882 - acc: 0.8290
Epoch 6/10
8000/8000 [==============================] - 1s 89us/step - loss: 0.3810 - acc: 0.8389
Epoch 7/10
8000/8000 [==============================] - 1s 88us/step - loss: 0.3755 - acc: 0.8432
Epoch 8/10
8000/8000 [==============================] - 1s 94us/step - loss: 0.3707 - acc: 0.8484
Epoch 9/10
8000/8000 [==============================] - 1s 91us/step - loss: 0.3671 - acc: 0.8510
Epoch 10/10
8000/8000 [==============================] - 1s 90us/ste

In [0]:
labels_pred=classifier.predict(features_test)

In [0]:
labels_pred=(labels_pred> 0.5)

In [0]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(labels_test, labels_pred)


In [44]:
cm

array([[1527,   68],
       [ 232,  173]])

In [0]:
x=np.array([0,0,600, 0, 40, 3,0, 1, 1, 1, 101349])

In [0]:
x=x.reshape(1,-1)

In [157]:

x.shape

(1, 11)

In [0]:
x=ss.fit_transform(x)

In [0]:
label_predicted=classifier.predict(x)

In [160]:
label_predicted

array([[0.08490234]], dtype=float32)